### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Alirezaaraby**
there is an error that occurred in your example 
image
I solved it with delete the additional quotation in the README file.

### CODE REVIEW

**Review by pate6240 — APPROVED** [review]

**Review by kylefairchild420 — APPROVED** [review]

**Review by Newman1515 — APPROVED** [review]

**Comment by Newman1515** [comment]
diff --git a/README.md b/README.md
index 5a27499..1b7f35b 100644
--- a/README.md
+++ b/README.md
@@ -11,8 +11,8 @@ steps:
 - uses: actions/first-interaction@v1
   with:
     repo-token: ${{ secrets.GITHUB_TOKEN }}
-    issue-message: '# Message with markdown.\nThis is the message that will be displayed on users' first issue.'
-    pr-message: 'Message that will be displayed on users' first pr. Look, a `code block` for markdown.'
+    issue-message: '# Message with markdown.\nThis is the message that will be displayed on users first issue.'
+    pr-message: 'Message that will be displayed on users first pr. Look, a `code block` for markdown.'
 ```
 
 # License

**Comment by Newman1515** [comment]
From 668eef3c29fa5eec1ee9014e8a22bf124327be90 Mon Sep 17 00:00:00 2001
From: Alirezaarabi <me@alirezaarabi.com>
Date: Thu, 7 Apr 2022 04:47:22 -0700
Subject: [PATCH] Update README.md

---
 README.md | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/README.md b/README.md
index 5a27499..1b7f35b 100644
--- a/README.md
+++ b/README.md
@@ -11,8 +11,8 @@ steps:
 - uses: actions/first-interaction@v1
   with:
     repo-token: ${{ secrets.GITHUB_TOKEN }}
-    issue-message: '# Message with markdown.\nThis is the message that will be displayed on users' first issue.'
-    pr-message: 'Message that will be displayed on users' first pr. Look, a `code block` for markdown.'
+    issue-message: '# Message with markdown.\nThis is the message that will be displayed on users first issue.'
+    pr-message: 'Message that will be displayed on users first pr. Look, a `code block` for markdown.'
 ```
 
 # License

**Review by Newman1515 — APPROVED** [review]

**Review by Newman1515 — COMMENTED** [review]
Here

**Review by Newman1515 — APPROVED** [review]

**Review by Newman1515 — APPROVED** [review]
Ya

**Review by mdtarekislam — APPROVED** [review]

**Review by Chana444 — COMMENTED** [review]
I'm not really understand how to make it work for me... Help please

**Review by Chana444 — APPROVED** [review]
How to make it

**Comment by Alirezaaraby** [comment]
> How to make it 

What do you mean?

**Review by DerOssi1 — APPROVED** [review]

**Comment by Alirezaaraby** [comment]
> Duplicate of #270 #271 #269  

The pull request id is 75 for this one so i think it was created sooner than these one you mentioned here.

**Review by Inggrid061190 — APPROVED** [review]

**Review by ncalteen — APPROVED** [review]

**Pull request merged**
