### PR TITLE
Updating bundled toolkit packages and fix error

### LINKED ISSUE #101: Import error when using the action in a workflow
Hey! Our team has been enjoying this action for a long time now, but today we started getting this error:

```
internal/modules/cjs/loader.js:1216
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /node_modules/@octokit/graphql/index.js
require() of ES modules is not supported.
require() of /node_modules/@octokit/graphql/index.js from /node_modules/@actions/github/lib/github.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/@octokit/graphql/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1216:13)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/node_modules/@actions/github/lib/github.js:14:19)
    at Module._compile (internal/modules/cjs/loader.js:1200:[30](https://github.com/creditornot/ops-tools/actions/runs/3150609247/jobs/5123593663#step:3:31))
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:[32](https://github.com/creditornot/ops-tools/actions/runs/3150609247/jobs/5123593663#step:3:33))
    at Function.Module._load (internal/modules/cjs/loader.js:9[37](https://github.com/creditornot/ops-tools/actions/runs/3150609247/jobs/5123593663#step:3:38):14) {
  code: 'ERR_REQUIRE_ESM'
}
```

### PR DESCRIPTION
**Pull request by thyeggman**
Fixes #101 

There was recently a change to the `@actions/github` [toolkit](https://github.com/actions/toolkit) package which itself uses `@octokit`.  Since we use pinned binary versions of all our packages for this action, they needed to be updated.

### CODE REVIEW

**Review by healchow — APPROVED** [review]
LGTM

**Comment by ruslanusmanov13** [comment]
Делаем.

**Review by benwells — APPROVED** [review]

**Review by thboop — APPROVED** [review]
lgtm

**Comment by pllim** [comment]
Hello and thanks! Which tag will contain this fix and when will it be tagged?

**Pull request merged**
