### PR TITLE
Escape single quote on README

### PR DESCRIPTION
**Pull request by georgeOsdDev**
Example in README has syntax error
https://github.com/actions/first-interaction/issues/8#issuecomment-529619857

### CODE REVIEW

**Review by 18-Aamina-18 — COMMENTED** [review]
Корисна інформація

**Review by ericboucher — APPROVED** [review]

**Review by William3Johnson — CHANGES_REQUESTED** [review]
Merge

**Review by William3Johnson — APPROVED** [review]

**Review by 18-Aamina-18 — APPROVED** [review]

**Review by Danastone — APPROVED** [review]

**Comment by internationalSSP** [comment]
> Hey

steps:
- uses: actions/first-interaction@v1
  with:
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    issue-message: '# Message with markdown.\nThis is the message that will be displayed on users' first issue.'
    pr-message: 'Message that will be displayed on users' first pr. Look, a `code block` for markdown.'

**Review by Lukajea — APPROVED** [review]

**Comment by Lukajea** [comment]
gh pr checkout 76

**Comment by ncalteen** [comment]
Closing as duplicate of #75

**Pull request closed without merging**
