### PR TITLE
Update cached licenses and added package-lock

### LINKED ISSUE #3: Warning missing package-lock.json file.
Currently there is no `package-lock.json` file.
This file is used to lock versions of dependencies.

This results in a WARN message stating you should add it.

```
 ---> c008d4cd2138
Step 3/4 : RUN npm install --production
 ---> Running in 9cde6380b3f4
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm notice created a lockfile as package-lock.json. You should commit this file.
added 54 packages from 33 contributors in 18.248s
Removing intermediate container 9cde6380b3f4
 ---> aeb402214f61
Step 4/4 : ENTRYPOINT ["node", "/lib/main.js"]
 ---> Running in f0802f57eb32
```

### PR DESCRIPTION
**Pull request by JeroenKnoops**
# Problem
Since the `package-lock.json` is missing, you're not sure what dependencies are used.
This will result in a mismatch in the cached licenses and the actual licenses.

This results in a failing licenses workflow, see issue #25 

# Solution
- [x] Add `package-lock.json`
- [x] Update cached licenses

## Related issues
Closes #3, #25

### CODE REVIEW

**Comment by rodrigoargumedo** [comment]
@JeroenKnoops I think adding `npm install -g npm@7.0.5` or `npm install -g npm@latest` should resolve this problem.

**Comment by JeroenKnoops** [comment]
> @JeroenKnoops I think adding `RUN npm install -g npm@7.0.5` or `RUN npm install -g npm@latest` to the dockerfile should resolve this problem.

Using `@latest` can result in the same type of errors in the future.. I would advise against that.

The reason the license check fails is because the cached license files are not matching the actual used dependencies.

I recommend either removing the license check with cached licenses yml files, or use a `package-lock.json` to make sure the dependencies are pinned.

**Comment by dakale** [comment]
LGTM, thanks @JeroenKnoops!

**Comment by sss6672** [comment]
patch

**Comment by Oceanside22** [comment]
commits @rone

**Pull request merged**
